musicvault.webapp/musicvault.webapp/Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace musicvault.webapp.Models
{
    public class Album
    {
        [Key]
        public virtual int Id { get; set; }
        [Required]
        public virtual int ArtistId { get; set; }        
        public virtual Artist Author { get; set; }
        public virtual List<Track> Tracks { get; set; }
        public virtual byte[] Cover { get; set; }
    }
}

musicvault.webapp/musicvault.webapp/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace musicvault.webapp.Models
{
    public class Artist
    {
        [Key]
        public virtual int Id { get; set; }
        [Required]
        public virtual string Name { get; set; }
    }
}

musicvault.webapp/musicvault.webapp/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace musicvault.webapp.Models
{
    public class Group : Artist
    {
        public virtual List<Artist> Members { get; set; }
    }
}

musicvault.webapp/musicvault.webapp/Models/MusicVaultContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace musicvault.webapp.Models
{
    public class MusicVaultContext : DbContext
    {
        public MusicVaultContext(DbContextOptions<MusicVaultContext> options) : base(options)
        {

        }

        public DbSet<Album> Albums { get; set; }
        public DbSet<Artist> Artists { get; set; }
        public DbSet<Group> Groups { get; set; }
    }
}

musicvault.webapp/musicvault.webapp/Models/Track.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace musicvault.webapp.Models
{
    public class Track
    {
        [Key]
        public virtual int Id { get; set; }
        [Required]
        public virtual int Number { get; set; }
        [Required]
        public virtual string Name { get; set; }
        [Required]
        public virtual byte Minutes { get; set; }
        [Required]
        public virtual byte Seconds { get; set; }
    }
}

musicvault.webapp/musicvault.webapp/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using musicvault.webapp.Models;

namespace musicvault.webapp.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly MusicVaultContext _context;

        public ArtistsController(MusicVaultContext context)
        {
            _context = context;    
        }

        // GET: Artists
        public async Task<IActionResult> Index()
        {
            return View(await _context.Artists.ToListAsync());
        }

        // GET: Artists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(artist);
        }

        // GET: Artists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.SingleOrDefaultAsync(m => m.Id == id);
            if (artist == null)
            {
                return NotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var artist = _context.Artists.Find(id);
            if (artist == null)
            {
                return NotFound();
            }
            if (await TryUpdateModelAsync<Artist>(artist, "", a => a.Name) && ModelState.IsValid)
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", string.Format("Unable to save changes: {0}", ex.Message));
                }
                return RedirectToAction("Index");
            }
            return View(artist);
        }

        // GET: Artists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.SingleOrDefaultAsync(m => m.Id == id);
            try
            {
                _context.Artists.Remove(artist);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", string.Format("Unable to save changes: {0}", ex.Message));
            }
            return RedirectToAction("Index");
        }

        private bool ArtistExists(int id)
        {
            return _context.Artists.Any(e => e.Id == id);
        }
    }
}

musicvault.webapp/musicvault.webapp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using musicvault.webapp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace musicvault.webapp.Controllers
{
    public class HomeController : Controller
    {
        #region Fields

        private MusicVaultContext _Context;

        #endregion

        #region Ctor

        public HomeController(MusicVaultContext context)
        {
            _Context = context;
        }

        #endregion

        #region Methods

        public IActionResult Index()
        {
            ViewBag.NumberOfArtists = _Context.Artists.Count();
            ViewBag.NumberOfAlbums = _Context.Albums.Count();
            return View();
        }

        #endregion
    }
}

musicvault.webapp/musicvault.webapp/Views/Artists/Create.cshtml
@model musicvault.webapp.Models.Artist

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create new artist</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

musicvault.webapp/musicvault.webapp/Views/Artists/Edit.cshtml
@model musicvault.webapp.Models.Artist

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

musicvault.webapp/musicvault.webapp/Views/Artists/Index.cshtml
@model IEnumerable<musicvault.webapp.Models.Artist>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Artists 
    <small><a asp-action="Create"><i class="fa fa-plus-square" aria-hidden="true" title="Add new"></i></a></small></h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-center">Edit</th>
            <th class="text-center">Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="text-center">
                    <a asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                </td>
                <td class="text-center">
                    <a asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure to delete this item?');"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

musicvault.webapp/musicvault.webapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div class="row">
    <div class="col-md-12">
        <h1>Hello, <small>Welcome to the Darth Dog's Music Vault</small></h1>        
        <ul class="list-group">
            <li class="list-group-item">
                <span class="badge">@ViewBag.NumberOfArtists</span>
                Number of artists
            </li>
            <li class="list-group-item">
                <span class="badge">@ViewBag.NumberOfAlbums</span>
                Number of albums
            </li>
        </ul>
    </div>
</div>

musicvault.webapp/musicvault.webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>DarthDog's Music Vault - @ViewData["Title"]</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/musicvault.css" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><i class="fa fa-music" aria-hidden="true"></i>&nbsp;Music Vault</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Artists" asp-action="Index">Artists</a></li>
                    <li><a asp-area="" asp-controller="Albums" asp-action="Index">Albums</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>